<template>
    <f7-page>
        <div class="vista">
    <nav-bar tipo="inicio" :backs="true" :title="'Términos y condiciones'"></nav-bar>
    <div class="contenedor-page-tabs">
        <div class="row w-100 m-0 back-color-blanco">
            <div class="row w-100 m-0 py-2 justify-content-center">
            <div class="col-12 text-justify mt-2" v-if="chofer" >
            <div class="row w-100 m-0 p-0 letra-gray3-25 white-space-preline text-justify py-3 justify-content-center">Términos y condiciones de uso de la aplicación Mivía Usuarios</div>
            <div class="row w-100 m-0 p-0 letra-gray2-18 white-space-preline text-justify py-3 justify-content-center">
MIVIA RIDES S.A. DE C.V. y su marca comercial Mivía, pone a su disposición los servicios que ofrece, según dicho término se define a continuación, de conformidad con los siguientes Términos y Condiciones que regulan el uso de la aplicación móvil de nombre de Mivía App Usuarios (en adelante el “la aplicación”) que puede ser descargada a través de Android, IOS o cualquier otro sistema, independientemente de los medios de acceso a ellos, tales como computadoras o dispositivos móviles (teléfonos inteligentes y tabletas); (I) el contenido de Mivía que aparezca en sitios web de terceros y redes sociales y (II) a los usuarios del sitio web, de las aplicaciones o de los servicios (indistintamente los “Términos y Condiciones” o el “Contrato”).

Estos Términos y Condiciones constituyen un acuerdo vinculante entre Usted y Mivía (la "Compañía," "Mivía" "Nosotros,", o "Nuestro") y se consideran aceptados por su parte cada vez que usted acceda al sitio web, y a la Aplicación o solicite cualquiera de los Servicios ofrecidos por Nosotros, en la versión publicada por Mivía, según sea el caso. Cualquier modificación a los presentes Términos y Condiciones será realizada por Mivía, cuando así lo considere apropiado, siendo exclusiva responsabilidad del Usuario asegurarse de tomar conocimiento de tales modificaciones.

El Usuario se sujetara a los presentes Términos y Condiciones respecto al uso adecuado de la aplicación Mivía App Usuario, por lo cual el usuario deberá de tener en cuenta que no podrá hacer uso de la aplicación y los servicios, si no ha proporcionado los datos, información y documentación requerida por la compañía para validar y dar de alta su perfil de usuario, así como leer de manera detenida, aceptar y cumplir con lo dispuesto en los presentes Términos y Condiciones; se entenderá como leídos y aceptados por parte del usuario al momento de firmarlos o dar clic en el botón de aceptar que ha leído y comprendido dichos términos. 

I. Reglas Generales de Uso

1. La información, consejos, contenidos, conceptos y opiniones publicadas en el Sitio Web o en la Aplicación no necesariamente reflejan la posición de Mivía ni de sus empleados, directores o accionistas. Por lo anterior, Mivía no se hace responsable por la información, consejos y opiniones que se emitan en el Sitio Web o en la Aplicación.
2. Mivía se reserva el derecho de bloquear el acceso o remover en forma parcial o total, toda información, comunicación o material que a su exclusivo juicio pueda resultar: 
    I. Abusivo, difamatorio, obsceno, ofensivo;
    II. Fraudulento, artificioso o engañoso;
    III. Violatorio de derechos de autor, marcas, confidencialidad, secretos industriales o cualquier derecho de propiedad intelectual de un tercero; o IV.Cualquier forma contravenga lo establecido en los presentes Términos y Condiciones.
3. “La aplicación” cuenta con uso exclusivo para usuarios (denominados en lo sucesivo como Clientes o Pasajeros) que, los cuales deben de ser de preferencia mayor de edad o de 16 años, de cualquier nacionalidad y género o sexo sin distinción alguna por cuestiones sociales, de raza, étnicas o religión, y deben de cumplir los requisitos de documentación requeridos por Mivía para darse de alta en la aplicación para poder solicitar y disfrutar de los servicios de transporte.
4. Mivía cuenta con administradores que en un panel de control validan y verifican los procesos de servicio.
II. Registro de los Conductores
1. Una vez validada la información proporcionada, así como entregados los requisitos necesarios para darse de alta como Conductor por parte de Mivía, el usuario (Conductor) deberá de descargar “la aplicación” en su dispositivo móvil, podrá completa su registro y darse de alta en “la aplicación” para poder prestar los servicios de transporte privado de pasajeros mediante aplicación en dispositivos móviles.
2. El Conductor reconoce y acepta que una vez registrado y dado de alta mediante su cuenta en “la aplicación” esta se quedará abierta de manera predeterminada.
3. El Conductor reconoce y manifiesta tener plena capacidad para el ejercicio de sus derechos así como de contraer obligaciones, asimismo asume total responsabilidad de los actos u omisiones que realice durante el tiempo que se mantenga activo en “la aplicación” para prestar los servicios de transporte privado de pasajeros mediante aplicación en dispositivos móviles. Acepta y reconoce que en todo momento se conducirá con respeto hacia los pasajeros y personal de la compañía.
4. El Conductor y/o Socio No Conductor reconoce y acepta sujetarse a los presentes términos y condiciones en todas y cada una de sus partes, así como acepta y reconoce que no existe, ni existirá relación laboral alguna de manera directa o indirecta entre ellos y la Compañía por el uso de la aplicación; dejando sin efecto la aplicación de cualquier norma jurídica o legislación en materia del trabajo y seguridad social.
III. Funcionamiento de Mivía App Conductor.
“La aplicación”en sus versiones de IOS y Android permite a 1 cliente solicitar 1 servicio de transporte privado a 1 destino dentro de la ciudad en la que opere la compañía. El usuario solicita el servicio y 1 afiliado (Conductor en un vehículo privado validado y acreditado por la compañía) de Mivía lo provee.
El Conductor reconoce que Mivía es un intermediario entre los afiliados y los clientes y no tiene ninguna responsabilidad en el servicio, la seguridad del usuario, el traslado, fallas mecánicas del auto, el destino, el tiempo de traslado, el clima y la ciudad de traslado. Por lo cual el Conductor asume total responsabilidad por los actos u omisiones que realice y ocasionen perjuicios al cliente o terceros, mientras se encuentre activo prestando el servicio dentro de “la aplicación”.
III. Obligaciones de los Conductores
Las obligaciones del Conductor y/o Socio no Conductor, son las que se listan a continuación de manera enunciativa pero no limitativa:
I. Proveer datos precisos y verídicos necesarios para registrarse y darse de alta como Conductor y/o Socio no Conductor, como lo es el nombre, datos de contacto, datos financieros y ubicación donde se proveerá el servicio;
II. Cumplir con el debido registro del o los vehículos con el o los que prestará el servicio ante la autoridad correspondiente, así como el registro ante autoridad correspondiente como conductor y/o Conductor de plataforma de transporte de pasajero mediante aplicación móvil; contar con licencia de conducir de Conductor vigente.
III. Sacar en paz y a salvo a Mivía en caso de incumplir con los términos de servicio e indemnizar a Mivía por cualquier acción legal que resulte en su contra;
IV. Contar con la computadora o dispositivo móvil que cumplan con las características y requisitos técnicos para acceder y utilizar la Aplicación, incluyendo la conexión a internet;
VI. No utilizar el Sitio Web para exhibir, transmitir, distribuir o vincular cualquier material que sea falso o engañoso, discriminatorio, difamatorio, ofensivo u obsceno o que pueda incitar a discriminación, odio o violencia contra una persona o grupo de personas a causa de su origen o pertenencia a un grupo étnico, raza o religión, a causa de su género o orientación sexual;
VII. Contar con póliza de seguro vigente y activo que ampare el servicio de multiplataforma o de servicio de transporte privado o público de pasajeros mediante aplicación en dispositivos móviles, con la cual garantice la cobertura de responsabilidad civil, hospitalización, gastos médicos de ocupantes y en su caso ampare muerte de conductor y ocupantes.
VIII. Contar con constancia certificada de no antecedentes penales, así como no antecedentes de consumo de drogas prohibidas por la legislación aplicable; no tener antecedentes de conducir bajo el influjo de alcohol o sustancias prohibidas por la legislación aplicable.
IX. Deberá el conductor de abstenerse de brindar el servicio de transporte privado de pasajeros mediante aplicación móvil, si cuenta con antecedentes o padece alguna de las siguientes enfermedades: enfermedades Cardiacas, Epilepsia, Vértigo, Histeria, Esquizofrenia, enfermedad de Parkinson, asimismo Psicopatías tales como demencia y enfermedades del sistema nervioso que afecten el uso de extremidades y capacidad de buenos reflejos, con la finalidad de salvaguardad tanto la integridad de los usuarios pasajeros y el propio conductor.
XI. El o los conductores deberán de contar con la legal posesión y dominio del o los vehículos registrados para prestar el servicio de transporte de pasajeros bajo demanda de aplicación móvil.
XII. Mantener en buen estado y en todo momento el o los vehículos tanto del exterior libre de polvo, rayones por daños y huellas de choque, en los interiores, los asientos deberán estar en todo momento limpios y ordenados, libres de desgaste. Las placas del o los vehículos deberán de estar claras y no cubrirlas o taparlas; no deberán de hacerse ninguna modificación ni decoración interior y exterior a los vehículos ya sea con pintura en aerosol o con vinil; abstenerse de colocar calcomanías publicitarias, accesorios, banderines ni otros adornos.
XIII. Contar con buena presencia y vestimenta al momento de estar prestando los servicios de transporte, adoptar una conducta y lenguaje apropiado, abstenerse se realizar actividades indebidas, así como beber bebidas alcohólicas o sustancias prohibidas por las leyes, de igual manera abstenerse de fumar tabaco o enervantes al interior del vehículo con o sin pasajero mientras este activo en la aplicación.
XIII. Mantener en todo momento actualizado el software y hardware de la aplicación en su teléfono o dispositivo móvil para poder cumplir y brindar los servicios de transporte mediante la aplicación, para lo cual de manera remota y automática se enviarán las notificaciones correspondientes para aceptar las actualizaciones correspondientes de la aplicación.
XIV. Abstenerse de usar los servicios de la aplicación para propósitos ilegales e indebidos, así como para acosar o afectar a terceros, tampoco afectar y dañar el funcionamiento normal de la aplicación, asimismo acepta y reconoce que usará los servicios de la aplicación de buena fe y cumplirá con todas las disposiciones jurídicas
y legislación aplicable en la ciudad que brindará el servicio, de igual manera a conducir con probidad respetando todas y cada una de las indicaciones y señales de tránsito, así como las leyes de la materia.
XV. Asistir y tomar los cursos de capacitación que estime necesario la empresa para mejorar las prácticas en la prestación del servicio y profesionalizar la atención al cliente.
XVI. Asumir todo el riesgo y responsabilidad por el incumplimiento de estas obligaciones.
IV. Del mecanismo de pago y comisión
El servicio de Mivía le es cobrado directamente al usuario (cliente) final ya sea mediante pago con tarjeta de crédito o débito y/o en efectivo, mediante un cálculo generado por el algoritmo de la aplicación, que toma como base el tiempo de traslado del viaje, distancia y el tráfico, de ese cobro, Mivía cobra un porcentaje de comisión por uso de la plataforma y el resto lo transfiere integro (menos la retención de impuestos correspondiente) al afiliado tipo Conductor en cortes semanales y/o quincenales según sea su conveniencia.
V. Comisión y cuota de servicio
I. El conductor acepta, reconoce y autoriza a Mivía para realizar el cobro de la comisión por uso de la plataforma de la aplicación para prestar el servicio de transporte privado de pasajero mediante aplicación móvil. Dicha acción le será notificada al conductor y desglosada de manera específica.
II. El conductor acepta y autoriza a Mivía para que realice las compensaciones correspondientes derivadas de las transacciones realizadas por pasajeros cuando estas hayan sido en pago con efectivo y se empatarán con los ingresos que el conductor tenga en su cuenta de la plataforma para posteriormente transferir lo debido a ambas partes.
III. El Conductor y/o Socio no Conductor, contara con una cuenta de usuario habilitada en la plataforma para revisar su balance de viajes e ingresos generados, pero en el caso de que algún conductor esté vinculado a un socio no conductor, no podrá retirar dinero ni realizar movimientos, ya que será el socio no conductor quien determine la manera en la cual entre ellos acuerden y pacten su modalidad de transferencias, dejando sin responsabilidad a Mivía.
IV. La tarifa y relación entre el Socio no Conductor y sus conductores vinculados será acordada entre ellos, Mivía no será responsable por las controversias que se llegaran a suscitar por el cobro de cuotas o tarifas con relación entre el Socio no Conductor y su o sus conductores vinculados.
VI. Facturación y retención de impuestos
I. El conductor y/o Socio no Conductor aceptan y reconocen que serán responsables de los pagos de impuestos y demás contribuciones gubernamentales que apliquen a la prestación del servicio de transporte privado de pasajeros mediante aplicación en dispositivos móviles y a los ingresos generados por dicho servicio o de cualquier otra actividad, pero sin limitarse a el Impuesto al Valor Agregado (IVA) y lo correspondiente a el Impuesto Sobre la Renta (ISR), así como reconoce la obligación de presentar las declaraciones correspondientes. Para tal efecto, El conductor y/o Socio no Conductor autoriza a Mivía para que de acuerdo con las disposiciones legales aplicables y con las autoridades fiscales correspondientes realice las retenciones de impuestos y demás contribuciones correspondientes y las entere a la autoridad fiscal en la forma y términos que así lo disponga.
II. El Conductor y/o Socio no Conductor reconoce y acepta que todos y cada uno de los comprobantes fiscales que el Pasajero requiera por los servicios de transporte que este preste, serán emitidos por el propio Conductor (o Socio No Conductor, en su caso), conforme con las leyes y reglamentos aplicables, y reconoce que, en su caso, el Socio No Conductor y el Conductor serán responsables solidarios por la emisión de comprobantes fiscales que reúnan los requisitos fiscales aplicables en México.
III. Mivía podrá, directamente o a través de un tercero, auxiliar a los Conductores y/o Socios No Conductores, para la emisión de comprobantes fiscales, para lo cual acepta y reconoce que dicho servicio generará un honorario mismo que debe ser cubierto por el Conductor y/o Socio no Conductor, autorizando a Mivía para realizar la retención directamente de los ingresos con los que cuente en su cuenta de usuario de la plataforma para el pago correspondiente por los honorarios al tercero que realice el servicio de auxilio con emisión de comprobantes y facturas fiscales, así como declaraciones u otros servicios requeridos.
El Conductor y/o Socio no Conductor acepta y reconoce que ni Mivía ni cualquier tercero designado por Mivía para tales efectos será responsable por cualquier error o falla en la emisión de los comprobantes fiscales correspondientes.
IV. Para el caso en el que el Conductor y/o Socio no Conductor acepte el auxilio y servicio para la emisión de comprobantes fiscales y facturas, deberá de entregar a Mivía toda la información necesaria para tal efecto, como es el caso de su Registro Federal de Contribuyentes (RFC) y su Certificado de Firma Digital (CSD) quien a su vez lo proporcionará a un tercero (Contador) autorizado por Mivía para que realice las actividades correspondientes. El RFC debe de entregarse desde el momento del registro para darse de alta en la plataforma y poder operar en la aplicación.
VII. Condiciones del Pago y Ofertas
Cualquier cargo hecho por la Compañía Mivía será exigible inmediatamente después de concluir el servicio y no será reembolsable.
Esta Política de no reembolso será aplicable en todo momento, independientemente de su decisión de suspender el uso del Sitio Web, la Aplicación o el Servicio. En caso de que el Cliente no esté conforme con los Servicios realizados podrá contactar al personal de Mivía quien podrá ofrecerle asistencia a través de los teléfonos que para tal efecto de tiempo en tiempo se publiquen en el Sitio Web.
La Compañía podrá, discrecionalmente, hacer ofertas o promocionales con diferentes características y diferentes tasas a cualquiera de los Clientes (Conductores y Usuarios). Estas ofertas o promocionales, a menos que se le haga a Usted, no tendrá influencia alguna en su oferta. Mivía puede cambiar los precios por el Servicio cuando lo considere necesario. Sugerimos revisar periódicamente el Sitio Web con el fin de revisar el precio de los Servicios y cualquier modificación que los mismos pudieren sufrir.
VIII. Responsabilidades y sanciones por incumplimiento del Conductor
I. Los usuarios de los servicios podrán calificar al conductor de acuerdo a la manera en la que se brindó el servicio de transporte, la actitud y trato que recibió por parte del conductor, la puntualidad y manera de conducir durante el viaje, así como la limpieza del vehículo. Este sistema de calificación se emplea como evaluación para mejorar las prácticas en la prestación del servicio y la calidad en atención al cliente.
II. El Conductor reconoce y acepta que se evalúe su prestación del servicio de acuerdo con lo mencionado en el párrafo anterior y autoriza que su calificación sea publicada en su perfil de conductor dentro de la aplicación para que los usuarios puedan observarla.
IX. Suspensión
Mivía podrá de manera discrecional suspender de manera temporal o definitiva de la aplicación a los conductores, que incumplan con lo dispuesto en los presentes términos y condiciones, así como las leyes que apliquen; notificando al conductor y explicando las circunstancias que dieron origen a la suspensión En el caso que estos incurran en actos constitutivos de delitos o que contravengan
con las disposiciones jurídicas en materia penal, administrativa y civil, Mivía podrá dar vista a la autoridad correspondiente para que se inicie el procedimiento jurídico al que haya lugar.
XI. Deslinde de Responsabilidad
El Conductor y/o Socio no Conductor están de acuerdo en que el uso del Sitio Web o de la Aplicación se realiza bajo su propio riesgo. Mivía no hace ningún tipo de representación ni otorga ningún tipo de garantía en cuanto a la confiabilidad, puntualidad, calidad, idoneidad, disponibilidad, exactitud o totalidad de los Servicios o del Sitio Web y la Aplicación. Mivía no garantiza que (I) el uso del Servicio será seguro, oportuno, ininterrumpido o libre de errores; (II) que el Servicio o el software del Sitio Web o la Aplicación cumplirá con sus necesidades o expectativas; (III) que la calidad de cualquier producto, Servicio, información u otro material obtenido por usted a través del Sitio Web, Aplicación o Servicio (incluyendo cualquier servicio de limpieza) cumplirá al cien por ciento los requerimientos del Cliente, sus necesidades o expectativas;y (IV) que el Sitio Web o la Aplicación estén libres de virus u otros componentes dañinos. El Software del Sitio Web y de la Aplicación así como los Servicio que se ofrecen en Mivía se prevén sobre una base “tal cual” y “según sean disponibles”.
Mivía no asume responsabilidad alguna por los daños y perjuicios de cualquier naturaleza que pudieran derivarse de la utilización de los Servicios y de los contenidos por parte de los Usuarios que puedan derivarse de la falta de veracidad, exhaustividad o autenticidad de la información que los Usuarios proporcionan, incluyendo pero no limitado a los daños y perjuicios que puedan derivarse de la suplantación de la personalidad de un tercero efectuada por un usuario en cualquier clase de comunicación realizada a través del Sitio Web o la Aplicación.
Mivía no asume ningún tipo de responsabilidad por los servicios de atención domiciliaria prestados por proveedores independientes y ajenos a Mivía, que se ostenten como tal, sin estar acreditados y validados por la compañía. Así mismo, no será responsable, bajo ninguna circunstancia de cualquier daño o perjuicio, directo o indirecto, causado en virtud de los Servicios contratados y facilitados a través del Sitio Web o de la Aplicación.
XII. Cancelación de Cuenta
Los Usuarios podrán en el momento que así lo deseen, cancelar su cuenta, en cuyo momento Mivía garantiza eliminar toda la información de dicho Usuario contenida en su cuenta. El proceso y ejercicio de Derechos ARCO está regulado por el Aviso de Privacidad y la Ley Federal de Protección de Datos Personales. No obstante lo anterior, Mivía se reserva el derecho y sin necesidad de aviso previo, de cancelar o suspender el derecho de cualquier Usuario de utilizar los Servicios, y bloquear e impedir su acceso y el uso de los Servicios si contravienen a lo dispuesto por estos términos y condiciones.
XIII. Derechos de Autor y Propiedad Industrial
Mivía sus logotipos, dominio, y todo el material que aparece en el Sitio Web y la Aplicación, son marcas, nombres de dominio y nombres comerciales propiedad de MI VIA RIDES S.A. de C.V. protegidos por tratados internacionales y leyes federales y locales en materia de propiedad intelectual y derechos de autor. Los derechos de autor sobre el contenido, organización, recopilación, información, logotipos, fotografías, imágenes, videos, programas, aplicaciones, o en general cualquier información contenida o publicada en el Sitio Web o en las Aplicaciones se encuentra debidamente protegida de conformidad con la legislación aplicable en materia de propiedad intelectual.
Se prohíbe expresamente al Usuario a modificar, alterar o suprimir, ya sea en forma total o parcial, los avisos, marcas, nombres comerciales, señas, anuncios, logotipos o en general cualquier indicación que se refiere a la propiedad de información contenida en el Sitio Web. El Usuario se obliga a no modificar, reproducir, copiar, rediseñar, descompilar, adaptar, traducir, preparar trabajos derivados de la Aplicación o del Sitio Web o utilizar la Aplicación para desarrollar cualquier software u otros materiales basados en los mismos.
XIV. Modificaciones a los presentes Términos y Condiciones
Mivía se reserva el derecho de modificar en cualquier momento que considere oportuno el contenido de estos Términos y Condiciones pudiendo adicionar provisiones relativas a áreas específicas o nuevos Servicios que en un futuro Mivía proporcione a través del Sitio Web o de las Aplicaciones, los cuales serán publicadas en el Sitio Web para su lectura y aceptación. Dichas modificaciones formarán parte integrante del presente contrato para todos los efectos legales a que haya lugar.
Es responsabilidad de los Usuarios verificar de tiempo en tiempo los presentes Términos y Condiciones para verificar el contenido de estos incluyendo cualquier cambio o modificación.
XV. Indemnización
Al hacer uso del Sitio Web, Aplicaciones y Servicios de Mivía, el Usuario consiente en indemnizar a MIVÍA, sus Afiliadas, accionistas, proveedores, vendedores y asesores de cualquier acción, demanda o reclamación (incluyendo honorarios de abogados y costas judiciales) derivadas de cualquier incumplimiento al presente Contrato por parte del Usuario.
XVI. Limitación de Responsabilidad
Mivía no será responsable frente a Usted ni frente a terceros por la no prestación de un Servicio pactado con cualquier conductor por fuera de la plataforma y aplicación de Mivía. En ningún caso y bajo ninguna circunstancia, Mivía, sus directores, empleados, agentes o accionistas serán responsables por los daños o perjuicios de cualquier tipo que surjan o se de alguna manera se relacionen con el uso o imposibilidad de usar el Servicio, el Sitio Web o la Aplicación, incluyendo sin limitación los daños provocados por la confianza depositada en el Usuario en cualquier información obtenida de Mivía, o como resultado de errores, omisiones, interrupciones, eliminación de archivos o correo electrónico, errores, defectos, virus, retrasos en la operación o transmisión o cualquier fallo de funcionamiento, sea éste ocasionado por desastres naturales, fallo de comunicaciones, robo, destrucción o acceso no autorizado a los registros de la Compañía. En ningún caso, la responsabilidad Mivía, derivada de un contrato, garantía, responsabilidad objetiva o de otro tipo, que surja en relación con el uso o imposibilidad de uso de los Servicios podrá superar la compensación que se pague en su caso a Mivía por el acceso o el uso de los Servicios.
XVII. Legislación Aplicable y Jurisdicción
El presente Contrato se regirá e interpretará de conformidad con las leyes de México, independientemente de las disposiciones relacionadas con conflictos de leyes.
Cualquier procedimiento de carácter legal que se derive o se relacione con este Contrato será dirimido en los tribunales competentes de la Ciudad de Guadalajara y en el Estado de Jalisco. Las partes del presente Contrato expresamente renuncian a cualquier otra jurisdicción que pudiera corresponderles en razón de su domicilio presente o futuro o por cualquier otra razón.
</div>
            </div>
                <div class="col-12 text-justify mt-2" v-if="user" >
                    <div class="row w-100 m-0 p-0 letra-gray3-25 white-space-preline text-justify py-3 justify-content-center">Términos y condiciones de uso de la aplicación Mivía Usuarios</div>
                    <div class="row w-100 m-0 p-0 letra-gray2-18 white-space-preline text-justify py-3 justify-content-center">MIVIA RIDES S.A. DE C.V. y su marca comercial Mivía, pone a su disposición los servicios que ofrece, según dicho término se define a continuación, de conformidad con los siguientes Términos y Condiciones que regulan el uso de la aplicación móvil de nombre de Mivía App Usuarios (en adelante el “la aplicación”) que puede ser descargada a través de Android, IOS o cualquier otro sistema, independientemente de los medios de acceso a ellos, tales como computadoras o dispositivos móviles (teléfonos inteligentes y tabletas); (I) el contenido de Mivía que aparezca en sitios web de terceros y redes sociales y (II) a los usuarios del sitio web, de las aplicaciones o de los servicios (indistintamente los “Términos y Condiciones” o el “Contrato”).

Estos Términos y Condiciones constituyen un acuerdo vinculante entre Usted y Mivía (la "Compañía," "Mivía" "Nosotros,", o "Nuestro") y se consideran aceptados por su parte cada vez que usted acceda al sitio web, y a la Aplicación o solicite cualquiera de los Servicios ofrecidos por Nosotros, en la versión publicada por Mivía, según sea el caso. Cualquier modificación a los presentes Términos y Condiciones será realizada por Mivía, cuando así lo considere apropiado, siendo exclusiva responsabilidad del Usuario asegurarse de tomar conocimiento de tales modificaciones.

El Usuario se sujetara a los presentes Términos y Condiciones respecto al uso adecuado de la aplicación Mivía App Usuario, por lo cual el usuario deberá de tener en cuenta que no podrá hacer uso de la aplicación y los servicios, si no ha proporcionado los datos, información y documentación requerida por la compañía para validar y dar de alta su perfil de usuario, así como leer de manera detenida, aceptar y cumplir con lo dispuesto en los presentes Términos y Condiciones; se entenderá como leídos y aceptados por parte del usuario al momento de firmarlos o dar clic en el botón de aceptar que ha leído y comprendido dichos términos. 

I. Reglas Generales de Uso

1. La información, consejos, contenidos, conceptos y opiniones publicadas en el Sitio Web o en la Aplicación no necesariamente reflejan la posición de Mivía ni de sus empleados, directores o accionistas. Por lo anterior, Mivía no se hace responsable por la información, consejos y opiniones que se emitan en el Sitio Web o en la Aplicación.
2. Mivía se reserva el derecho de bloquear el acceso o remover en forma parcial o total, toda información, comunicación o material que a su exclusivo juicio pueda resultar: 
    I. Abusivo, difamatorio, obsceno, ofensivo;
    II. Fraudulento, artificioso o engañoso;
    III. Violatorio de derechos de autor, marcas, confidencialidad, secretos industriales o cualquier derecho de propiedad intelectual de un tercero; o IV.Cualquier forma contravenga lo establecido en los presentes Términos y Condiciones.
3. “La aplicación” cuenta con uso exclusivo para usuarios (denominados en lo sucesivo como Clientes o Pasajeros) que, los cuales deben de ser de preferencia mayor de edad o de 16 años, de cualquier nacionalidad y género o sexo sin distinción alguna por cuestiones sociales, de raza, étnicas o religión, y deben de cumplir los requisitos de documentación requeridos por Mivía para darse de alta en la aplicación para poder solicitar y disfrutar de los servicios de transporte.
4. Mivía cuenta con administradores que en un panel de control validan y verifican los procesos de servicio. 
II. Registro de los Usuarios en la aplicación
1. Una vez descargada e instalada la aplicación en su dispositivo móvil, el usuario deberá de registrarse y seguir el proceso para darse de alta como cliente, proporcionando la siguiente información:
    a) Datos generales como nombre, teléfono celular, correo electrónico.
    b) Adjuntar en fotografía alguna identificación oficial vigente (Pasaporte,
    Credencial para votar o licencia.) con la finalidad de autentificar los
    datos proporcionados y verificar su identidad.
    c) Adjuntar fotografía para su perfil de usuario (opcional).
    d) Datos sobre el método de pago con tarjeta, vinculando una o varias tarjetas ya sean de crédito o débito.

Una vez validados los datos y cotejada la información del usuario por parte de Mivía, el usuario podrá hacer uso y goce de los servicios de la aplicación.

2. El Usuario reconoce y acepta que una vez registrado y dado de alta mediante su cuenta en “la aplicación” esta se quedará abierta de manera predeterminada y recibirá alertas o notificaciones referentes a la aplicación.

3. El Usuario reconoce y manifiesta tener plena capacidad para el ejercicio de sus derechos así como de contraer obligaciones, asimismo asume total responsabilidad de los actos u omisiones que realice durante el tiempo que se mantenga activo disfrutando de los servicios de transporte por medio de tercero que brinda “la aplicación”. Acepta y reconoce que en todo momento se conducirá con respeto hacia los Conductores y personal de la compañía.

4. El Usuario reconoce y acepta sujetarse a los presentes términos y condiciones en todas y cada una de sus partes. 

III. Funcionamiento de Mivía App Usuario.
“La aplicación”en sus versiones de IOS y Android permite a 1 cliente solicitar 1 servicio de transporte privado a 1 destino dentro de la ciudad en la que opere. El usuario solicita el servicio y 1 afiliado (Conductor en un vehículo privado validado y acreditado por la compañía) de Mivía lo provee.
El Usuario reconoce que Mivía es un intermediario entre los afiliados conductores y los clientes y no tiene ninguna responsabilidad en el servicio, la seguridad del usuario, el traslado, fallas mecánicas del auto, el destino, el tiempo de traslado, el clima y la ciudad de traslado. Por lo cual el Usuario asume total responsabilidad por los actos u omisiones que realice y ocasionen perjuicios al conductor o terceros, mientras se encuentre activo haciendo uso y gozando del servicio de transporte dentro de “la aplicación”.

III. Obligaciones de los Usuarios

Las obligaciones del Usuario o cliente, son las que se listan a continuación de manera enunciativa pero no limitativa:
I. Proveer datos precisos y verídicos necesarios para registrarse y darse de alta como Usuario, como lo es el nombre, datos de contacto, datos financieros y ubicación donde se proveerá el servicio;
II. Cumplir con el debido registro como usuario en la aplicación para poder contar con su perfil de usuario;
III. Sacar en paz y a salvo a Mivía en caso de incumplir con los términos de servicio e indemnizar a Mivía por cualquier acción legal que resulte en su contra;
IV. Contar con la computadora o dispositivo móvil que cumplan con las características y requisitos técnicos para acceder y utilizar la Aplicación, incluyendo la conexión a internet;
VI. No utilizar el Sitio Web para exhibir, transmitir, distribuir o vincular cualquier material que sea falso o engañoso, discriminatorio, difamatorio, ofensivo u obsceno o que pueda incitar a discriminación, odio o violencia contra una persona o grupo de personas a causa de su origen o pertenencia a un grupo étnico, raza o religión, a causa de su género o orientación sexual;
V. Deberá el Usuario de abstenerse de adoptar conductas inapropiadas durante el trayecto de su viaje y dirigirse con respeto hacia el conductor, así como respetar y mantener en orden el estado en el que se encuentre el vehículo en el cual le sea brindado el servicio;

VI. Abstenerse de ingerir alimentos durante el trayecto de su viaje, así como evitar el consumo de bebidas alcohólicas o sustancias prohibidas por las leyes, asimismo esta determinadamente prohibido fumar tabaco o enervantes al interior del vehículo durante el trayecto de su viaje;
VII. Mantener en todo momento actualizado el software y hardware de la aplicación en su teléfono o dispositivo móvil para poder gozar de los servicios de transporte mediante la aplicación, para lo cual de manera remota y automática se enviarán las notificaciones para aceptar las actualizaciones correspondientes de la aplicación;
VIII. Abstenerse de usar los servicios de la aplicación para propósitos ilegales e indebidos, así como para acosar o afectar a terceros, tampoco afectar y dañar el funcionamiento normal de la aplicación, asimismo acepta y reconoce que usará los servicios de la aplicación de buena fe y cumplirá con todas las disposiciones jurídicas y legislación aplicable en la ciudad que brindará el servicio; y IX. Asumir todo el riesgo y responsabilidad por el incumplimiento de estas obligaciones.
IV. Del mecanismo de pago y comisión El servicio de Mivía le es cobrado directamente al usuario (cliente) final ya sea mediante pago con tarjeta de crédito o débito y/o en efectivo, mediante un cálculo generado por el algoritmo de la aplicación, que toma como base el tiempo de traslado del viaje, distancia, el tráfico y una cuota de solicitud o tarifa base de acuerdo a cada uno de los servicios que brinda, de ese cobro, Mivía cobra un porcentaje de comisión por uso de la plataforma y el resto lo transfiere integro (menos la retención de impuestos correspondiente) al afiliado tipo Conductor en cortes semanales y/o quincenales según sea su conveniencia.
V. Tarifas y cuotas de servicio
I. El Usuario podrá realizar el pago por uso de los servicios, ya sea mediante pago en efectivo o tarjeta de crédito o débito previamente vinculado en su perfil de usuario en la aplicación, deberá de privilegiar en todo momento el pago con tarjeta.
II. El Usuario acepta, reconoce y autoriza a Mivía para realizar el cobro de la cuota por viaje que realice por medio de la aplicación para el servicio de transporte privado de pasajero mediante aplicación móvil, para lo cual Mivía hará los cargos directos a la o las tarjetas vinculadas en el perfil del usuario en la aplicación. Dicha acción le será notificada al Usuario y desglosada de manera específica.
III. Las tarifas serán establecidas por Mivía y serán publicadas tanto en la plataforma como en la aplicación y en el sitio web para que los usuarios puedan consultarlas, también en tiempo real, antes de solicitar cualquier servicio se pondrá a disposición del usuario en la aplicación una cotización aproximada del costo total por el viaje que pretenda realizar el usuario. Estas tarifas pueden incrementar de manera repentina debido a circunstancias de alta demanda del servicio cerca de la ubicación del usuario que solicite el viaje, asimismo por cuestiones climatológicas o de tráfico. De acuerdo con lo anterior el Usuario reconoce y acepta las disposiciones de las tarifas establecidas con todo y sus diferentes circunstancias.
IV. El Usuario reconoce y acepta que existe una cuota de cancelación, la cual consiste en el cobro que se aplicará al usuario, si este cancela el viaje después del tiempo de gracia de 3 minutos contados desde el momento en que se acepta de manera exitosa el viaje por el chofer afiliado a la aplicación.
El usuario contará con opciones de cancelación y/o aclaración para el reembolso de la cuota de cancelación siempre y cuando el motivo de la misma se encuentre dentro de los supuestos en que no sea inimputable a él.
Si el chofer demora mucho tiempo en llegar al punto de partida del viaje solicitado por el Usuario, de manera automática se enviará la solicitud a otro chofer que se encuentre cerca al punto de solicitud para brindar el servicio, en su defecto podrá el Usuario cancelar sin que se aplique la cuota de cancelación, ya que se actualizará de nuevo el tiempo de gracia de 3 minutos para cancelar sin cobro.
VI. Facturación y retención de impuestos
I. El Usuario acepta y reconoce que será responsable de los pagos de impuestos y demás contribuciones gubernamentales que apliquen a la prestación del servicio de transporte privado de pasajeros mediante aplicación en dispositivos móviles, siendo lo correspondiente al Impuesto al Valor Agregado (IVA), la contribución gubernamental y la cuota de solicitud.
II. El Usuario reconoce y acepta que podrá solicitar sus comprobantes fiscales por los servicios recibidos, mismos que serán solicitados y emitidos directamente por los Conductores y/o Socios no Conductores Pasajero, conforme con las leyes y reglamentos aplicables, asimismo reconoce que, cualquier error en la emisión de comprobantes fiscales será única y exclusivamente responsabilidad de quien lo emita, dejando sin responsabilidad por dichos actos a Mivía.
VII. Condiciones del Pago y Ofertas.
Cualquier cargo hecho por la Compañía Mivía será exigible inmediatamente después de concluir el servicio y no será reembolsable.
Esta Política de no reembolso será aplicable en todo momento, independientemente de su decisión de suspender el uso del Sitio Web, la Aplicación o el Servicio. En caso de que el Cliente no esté conforme con los Servicios realizados podrá contactar al personal de Mivía quien podrá ofrecerle asistencia a través de los teléfonos que para tal efecto de tiempo en tiempo se publiquen en el Sitio Web.
La Compañía podrá, discrecionalmente, hacer ofertas o promocionales con diferentes características y diferentes tasas a cualquiera de los Clientes (Conductores y Usuarios). Estas ofertas o promocionales, a menos que se le haga a Usted, no tendrá influencia alguna en su oferta. Mivía puede cambiar los precios por el Servicio cuando lo considere necesario. Sugerimos revisar periódicamente el Sitio Web con el fin de revisar el precio de los Servicios y cualquier modificación que los mismos pudieren sufrir.
VIII. Responsabilidades y sanciones por incumplimiento del Conductor
I. Los Conductores que brindan el servicio de transporte privado de pasajeros, podrán calificar al Usuario de acuerdo al comportamiento que adopto este último, antes durante y al finalizar su viaje, tomando como parámetros, la actitud y trato que recibió por parte del Usuario. Este sistema de calificación se emplea como evaluación para mejorar las prácticas en la prestación del servicio y la calidad en atención al cliente.
II. El Usuario reconoce y acepta que se evalúe su conducta durante la prestación del servicio, de acuerdo con lo mencionado en el párrafo anterior y autoriza que su calificación sea publicada en su perfil de usuario dentro de la aplicación para que los Conductores puedan observarla.
IX. Suspensión
Mivía podrá de manera discrecional suspender de manera temporal o definitiva de la aplicación a los Usuarios, que incumplan con lo dispuesto en los presentes términos y condiciones; notificando al Usuario y explicando las circunstancias que dieron origen a la suspensión.
En el caso que estos incurran en actos constitutivos de delitos o que contravengan con las disposiciones jurídicas en materia penal, administrativa y civil, Mivía podrá dar vista a la autoridad correspondiente para que se inicie el procedimiento jurídico al que haya lugar.
XI. Deslinde de Responsabilidad
El Usuario está de acuerdo en que el uso del Sitio Web o de la Aplicación se realiza bajo su propio riesgo. Mivía no hace ningún tipo de representación ni otorga ningún tipo de garantía en cuanto a la confiabilidad, puntualidad, calidad, idoneidad, disponibilidad, exactitud o totalidad de los Servicios o del Sitio Web y la Aplicación. Mivía no garantiza que (I) el uso del Servicio será seguro, oportuno, ininterrumpido o libre de errores; (II) que el Servicio o el software del Sitio Web o la Aplicación cumplirá con sus necesidades o expectativas; (III) que la calidad de cualquier producto, Servicio, información u otro material obtenido por usted a través del Sitio Web, Aplicación o Servicio (incluyendo cualquier servicio de limpieza) cumplirá al cien por ciento los requerimientos del Cliente, sus necesidades o expectativas;y (IV) que el Sitio Web o la Aplicación estén libres de virus u otros componentes dañinos. El Software del Sitio Web y de la Aplicación así como los Servicio que se ofrecen en Mivía se prevén sobre una base “tal cual” y “según sean disponibles”.
Mivía no asume responsabilidad alguna por los daños y perjuicios de cualquier naturaleza que pudieran derivarse de la utilización de los Servicios y de los contenidos por parte de los Usuarios que puedan derivarse de la falta de veracidad, exhaustividad o autenticidad de la información que los Usuarios proporcionan, incluyendo pero no limitado a los daños y perjuicios que puedan derivarse de la suplantación de la personalidad de un tercero efectuada por un usuario en cualquier clase de comunicación realizada a través del Sitio Web o la Aplicación.
Mivía no asume ningún tipo de responsabilidad por los servicios de atención domiciliaria prestados por proveedores independientes y ajenos a Mivía, que se ostenten como tal, sin estar acreditados y validados por la compañía. Así mismo, no será responsable, bajo ninguna circunstancia de cualquier daño o perjuicio, directo o indirecto, causado en virtud de los Servicios contratados y facilitados a través del Sitio Web o de la Aplicación.
XII. Cancelación de Cuenta
Los Usuarios podrán en el momento que así lo deseen, cancelar su cuenta, en cuyo momento Mivía garantiza eliminar toda la información de dicho Usuario contenida en su cuenta. El proceso y ejercicio de Derechos ARCO está regulado por el Aviso de Privacidad y la Ley Federal de Protección de Datos Personales. No obstante lo anterior, Mivía se reserva el derecho y sin necesidad de aviso previo, de cancelar o suspender el derecho de cualquier Usuario de utilizar los Servicios, y bloquear e impedir su acceso y el uso de los Servicios si contravienen a lo dispuesto por estos términos y condiciones.
XIII. Derechos de Autor y Propiedad Industrial
Mivía sus logotipos, dominio, y todo el material que aparece en el Sitio Web y la Aplicación, son marcas, nombres de dominio y nombres comerciales propiedad de MI VIA RIDES S.A. de C.V. protegidos por tratados internacionales y leyes federales y locales en materia de propiedad intelectual y derechos de autor. Los derechos de autor sobre el contenido, organización, recopilación, información, logotipos, fotografías, imágenes, videos, programas, aplicaciones, o en general cualquier información contenida o publicada en el Sitio Web o en las Aplicaciones se encuentra debidamente protegida de conformidad con la legislación aplicable en materia de propiedad intelectual.
Se prohíbe expresamente al Usuario a modificar, alterar o suprimir, ya sea en forma total o parcial, los avisos, marcas, nombres comerciales, señas, anuncios, logotipos o en general cualquier indicación que se refiere a la propiedad de información contenida en el Sitio Web. El Usuario se obliga a no modificar, reproducir, copiar, rediseñar, descompilar, adaptar, traducir, preparar trabajos derivados de la Aplicación o del Sitio Web o utilizar la Aplicación para desarrollar cualquier software u otros materiales basados en los mismos.
XIV. Modificaciones a los presentes Términos y Condiciones
Mivía se reserva el derecho de modificar en cualquier momento que considere oportuno el contenido de estos Términos y Condiciones pudiendo adicionar provisiones relativas a áreas específicas o nuevos Servicios que en un futuro Mivía proporcione a través del Sitio Web o de las Aplicaciones, los cuales serán publicadas en el Sitio Web para su lectura y aceptación. Dichas modificaciones formarán parte integrante del presente contrato para todos los efectos legales a que haya lugar.
Es responsabilidad de los Usuarios verificar de tiempo en tiempo los presentes Términos y Condiciones para verificar el contenido de estos incluyendo cualquier cambio o modificación.
XV. Indemnización
Al hacer uso del Sitio Web, Aplicaciones y Servicios de Mivía, el Usuario consiente en indemnizar a MIVÍA, sus Afiliadas, accionistas, proveedores, vendedores y asesores de cualquier acción, demanda o reclamación (incluyendo honorarios de abogados y costas judiciales) derivadas de cualquier incumplimiento al presente Contrato por parte del Usuario.
XVI. Limitación de Responsabilidad
Mivía no será responsable frente a Usted ni frente a terceros por la no prestación de un Servicio pactado con cualquier conductor por fuera de la plataforma y aplicación de Mivía. En ningún caso y bajo ninguna circunstancia, Mivía, sus directores, empleados, agentes o accionistas serán responsables por los daños o perjuicios de cualquier tipo que surjan o se de alguna manera se relacionen con el uso o imposibilidad de usar el Servicio, el Sitio Web o la Aplicación, incluyendo sin limitación los daños provocados por la confianza depositada en el Usuario en cualquier información obtenida de Mivía, o como resultado de errores, omisiones, interrupciones, eliminación de archivos o correo electrónico, errores, defectos, virus, retrasos en la operación o transmisión o cualquier fallo de funcionamiento, sea éste ocasionado por desastres naturales, fallo de comunicaciones, robo, destrucción o acceso no autorizado a los registros de la Compañía. En ningún caso, la responsabilidad Mivía, derivada de un contrato, garantía, responsabilidad objetiva o de otro tipo, que surja en relación con el uso o imposibilidad de uso de los Servicios podrá superar la compensación que se pague en su caso a Mivía por el acceso o el uso de los Servicios.
XVII. Legislación Aplicable y Jurisdicción
El presente Contrato se regirá e interpretará de conformidad con las leyes de México, independientemente de las disposiciones relacionadas con conflictos de leyes. Cualquier procedimiento de carácter legal que se derive o se relacione con este Contrato será dirimido en los tribunales competentes de la Ciudad de Guadalajara y en el Estado de Jalisco. Las partes del presente Contrato expresamente renuncian a cualquier otra jurisdicción que pudiera corresponderles en razón de su domicilio presente o futuro o por cualquier otra razón.
</div>
                </div>
            </div>
        </div>
    </div>
</div>
    </f7-page>
</template>
<script>

import { f7Page } from 'framework7-vue';
import Swiper from 'swiper';
export default{
    components:{
        f7Page,
    },
    data(){
        return{
            promos_slider: null,
            categorias_slider: null
        } 
    },
    computed: {
        session(){return this.$store.getters.getSession;},
        user(){return this.$store.getters.user;},
        chofer(){return this.$store.getters.chofer;},
    },
    methods:{
        goTo(ruta){
            this.$f7.views.principal.router.navigate(ruta);
        },
        goToDetelle(){
            this.goTo('/mensajes_chat');
        }
    }
}
</script>